# # Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# target 'ZooPass' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#
rn_maps_path = '../node_modules/react-native-maps'
#pod 'react-native-maps', path: rn_maps_path
pod 'react-native-google-maps', path: rn_maps_path
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'
#   target 'ZooPassTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#   use_native_modules!
#   post_install do |pi|
#     pi.pods_project.targets.each do |t|
#       t.build_configurations.each do |config|
#         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
#       end
#     end
#   end
# end

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'ZooPass' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ZooPassTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_frameworks!
  use_flipper!({'Flipper' => '0.87.0' , 'Flipper-Folly' => '2.5.3' , 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
